### ISSUE TITLE
new terms: Diffusion weighted MRI Abnormality

### ISSUE THREAD

**Issue by yankeetomer** [TheJacksonLaboratory/hpo-web#101]
HPO does not currently have any entries that describe DWI abnormalities. 

1. Preferred term label
Diffusion weighted MRI Abnormality

2. Synonyms

Diffusion weighted magnetic resonance imaging (DWI) abnormality
Diffusion weighted imaging (DWI) abnormality
MRI diffusion abnormality

Drug resistance
3. Textual definition (should be understandable even for non-specialists, please include a PubMed ID for relevant articles providing additional information about the suggestion)
Neurol Clin Pract. 2012 Dec; 2(4): 287–293.
doi: 10.1212/CPJ.0b013e318278bee1 :

Restricted diffusion is an imaging finding typically associated with acute cerebral infarction. Less frequently this MRI abnormality is seen with other conditions including neoplasms, intracranial infections, traumatic brain injury, and demyelinating processes.

> The vast majority of restricted-diffusion abnormalities result from acute stroke, and as such, the diagnosis may be problematic when this MRI feature results from other causes. Distinct patterns of restricted diffusion seen with various disease conditions can play an important diagnostic role. The association of certain diseases with a given restricted-diffusion pattern allows for a focused assessment to determine a specific etiology.

4. Parent term
Abnormality of brain morphology 
HP:0012443
(http://compbio.charite.de/hpoweb/showterm?id=HP:0012443)

5. Which diseases are characterized by this term ? (e.g. Orphanet- or OMIM-id)
One example:
Leigh Syndrome in a recent article appearing in Genetics in Medicine:
"Axial diffusion-weighted imaging (F) shows bilateral symmetrical diffusion restriction in the putamina, thalami, and hippocampal tails"
https://www.sciencedirect.com/science/article/pii/S0002929719304653
DOI:https://doi.org/10.1016/j.ajhg.2019.12.001

6. Your nano-attribution
Tomer Talmy M.D.
Organization: Emedgene Technologies
ORCID: https://orcid.org/0000-0002-7440-8864

**Comment by iimpulse** [comment]
Hi @yankeetomer are you able to recreate this request here. https://github.com/obophenotype/human-phenotype-ontology/issues with the tag new term request? Thanks!

**Comment by yankeetomer** [comment]
Added as new term request, this issue can can now be closed
