### ISSUE TITLE
Link from obo foundry broken

### ISSUE THREAD

**Issue by kshefchek** [TheJacksonLaboratory/hpo-web#104]
http://www.obofoundry.org/ontology/hp.html links to https://hpo.jax.org/app/browse/term/?id=HP:0000118, but should probably link to https://hpo.jax.org/app/browse/term/HP:0000118 (not really a hpo ui issue but rather obofoundy unless the former should forward to the latter)

**Comment by nomisto** [comment]
I have got the same issue with identifiers.org/HP:0000118

**Comment by iimpulse** [comment]
This appears to be fixed.
