### ISSUE TITLE
Gene-phenotype annotation file differs from website annotation

### ISSUE THREAD

**Issue by frequena** [TheJacksonLaboratory/hpo-web#105]
Dear HPO-web team,

I downloaded the next file: 

http://compbio.charite.de/jenkins/job/hpo.annotations.monthly/lastStableBuild/artifact/annotation/ALL_SOURCES_ALL_FREQUENCIES_genes_to_phenotype.txt

...and I checked there are mismatches between HPO terms and associated genes.

For instance, the term "HP:0000223"  is associated with 6 genes but it does not appear on the file.

In the same way, there are other HPO terms that are displayed on the website but not in the file.

Thank you!

**Comment by iimpulse** [comment]
Hi @frequena, sorry for such a delayed response, currently we've moved to a new annotation format https://hpo.jax.org/app/download/annotation

We provide an hpoa file, and then map genes to diseases via provided files from orpha and omim, and currently do not provide these mappings besides what is downloadable from the site.  We are working to improve our pipelines and provide these new mappings as files.

**Comment by frequena** [comment]
Hello @iimpulse, I was just concerned about the integrity of the data because of any unintentional mismatch between the raw file and the web data. But I completely understand now :)

Thank you for your work!
