### ISSUE TITLE
Typo in HP:0000044

### ISSUE THREAD

**Issue by pcoenen** [TheJacksonLaboratory/hpo-web#106]
We think we  noticed a little typo in HP:0000044 'Hypogonadotrophic hypogonadism'. 

Shouldn't it be 'Hypogonadotropic hypogonadism', instead of 'Hypogonadotrop**h**ic hypogonadism'?

**Comment by pnrobinson** [comment]
I am going to transfer this to the main HPO repo

**Comment by pnrobinson** [comment]
https://github.com/obophenotype/human-phenotype-ontology/issues/5498
