### ISSUE TITLE
OMIM name not resolved correctly

### ISSUE THREAD

**Issue by drseb** [TheJacksonLaboratory/hpo-web#111]
This omim entry https://www.omim.org/entry/314570 is shown like this:

<img width="659" alt="Screenshot 2020-02-26 at 09 21 40" src="https://user-images.githubusercontent.com/5172897/75325951-0d437300-587a-11ea-82aa-4a5c6b3daab7.png">

**Comment by iimpulse** [comment]
@drseb Seems resolved? Going to close please re-open if you still see it.
