### ISSUE TITLE
Wrong download link

### ISSUE THREAD

**Issue by leonschuetz** [TheJacksonLaboratory/hpo-web#112]
Hello,

the download link on [https://hpo.jax.org/app/download/annotation](https://hpo.jax.org/app/download/annotation) for the **phenotype.hpoa** file and the links for the additional resources do not seem to work.

Best regards,
Leon

**Comment by pnrobinson** [comment]
Thanks for pointing this out.
The link is out of date:
/jenkins/job/hpo.annotations.current/lastSuccessfulBuild/artifact/misc_2018/phenotype.hpoa

The correct link is
http://compbio.charite.de/jenkins/job/hpo.annotations.current/lastSuccessfulBuild/artifact/current/phenotype.hpoa

**Comment by pnrobinson** [comment]
@iimpulse  Can we update this page?

**Comment by iimpulse** [comment]
Updated in production #114  thanks.
