### ISSUE TITLE
Search results issue

### ISSUE THREAD

**Issue by krhms3** [TheJacksonLaboratory/hpo-web#121]
Hi,
When I search either a disease term or a phenotype term - I get a result like this - with the word 'inheritance' and a list of annotations.   How do I fix this?    
Thank you,
Karen Hanson, MS, MBA

![image](https://user-images.githubusercontent.com/63014008/78171569-a2f69300-7422-11ea-9536-1804cf18673a.png)

**Comment by pnrobinson** [comment]
We just noticed this bug a few days ago and are working on a fix. The annotations are correct, but the category ("Inheritance") is broken. There should be a new version out by next week.

**Comment by iimpulse** [comment]
Hi @krhms3, 

We've addressed the categories issues in production. The correct category should now be showing for relevant hpo terms to a disease. 

If you see anything else feel free to either re-open this issue or submit a new one :)
