### ISSUE TITLE
0000989 this id not located in the Database 

### ISSUE THREAD

**Issue by shoaib03339770257** [TheJacksonLaboratory/hpo-web#124]
i search it but the system take me to error with unknow situation and than take here to put the issue about the HPO

**Comment by iimpulse** [comment]
hi @shoaib03339770257, seems like our searching isnt as robust, you must type the prefix as well or the name,  so either "HP:0000989" or "Pruritus". I'll log this as a bug to enhance our searching.

Here is your page: https://hpo.jax.org/app/browse/term/HP:0000989
