### ISSUE TITLE
ALL_SOURCES_FREQUENT_FEATURES_genes_to_phenotype

### ISSUE THREAD

**Issue by jpinero** [TheJacksonLaboratory/hpo-web#129]
Hi!
what happened to the file ALL_SOURCES_FREQUENT_FEATURES_genes_to_phenotype.txt that used to be here http://compbio.charite.de/jenkins/job/hpo.annotations/lastStableBuild/ ?
or more precisely, here 
	http://compbio.charite.de/jenkins/job/hpo.annotations.monthly/lastStableBuild/artifact/annotation/ALL_SOURCES_FREQUENT_FEATURES_genes_to_phenotype.txt
thanks

**Comment by pnrobinson** [comment]
The new resources are described here:

https://hpo.jax.org/app/download/annotation

Please let us know if you have suggestions about the format or the documentation
@drseb

**Comment by drseb** [comment]
@jpinero please read the mailing-list announcement here: https://groups.io/g/human-phenotype-ontology/message/16
you might also want to consider joining this mailing-list.

thanks,
seb

**Comment by jpinero** [comment]
Hi, 
thanks for the quick response. I have joined the mail list. It is still not clear to me if there is a way to generate the FREQUENT_FEATURES from the new file genes_to_phenotype.txt. My guess would be no, because the frequency annotations are spare, right?

**Comment by drseb** [comment]
yes you should be able to generate that file. Previously we assumed for all associations with no frequency information a frequency of 1.

best seb
