### ISSUE TITLE
Redesign the browser

### ISSUE THREAD

**Issue by iimpulse** [TheJacksonLaboratory/hpo-web#130]
There are some nice tree widgets out there now with d3. Look into enhancing our left browser on term pages or consider this with an implementation of #13

**Comment by pnrobinson** [comment]
@iimpulse Another option would be to use the OLS broswer, see:https://ols.monarchinitiative.org/ontologies/hp

In any case, we should link to this site. It has the last develop version. 

Could we add a page under Documentation|Other called
Develop version

With text:

The HPO is released every two months. The very latest develop version is always available at the HPO GitHub site (https://github.com/obophenotype/human-phenotype-ontology). Users can browse the develop version using our OLS instance at https://ols.monarchinitiative.org/ontologies/hp.
