### ISSUE TITLE
008207 link broken

### ISSUE THREAD

**Issue by LAB123GO** [TheJacksonLaboratory/hpo-web#132]
On this page:  https://rarediseases.info.nih.gov/diseases/7611/autoimmune-polyglandular-syndrome-type-2

Autoimmune polyglandular syndrome type 2
Table:  (Primary Adrenal Insufficiency 008207 link doesn't work.  Please fix!  Thank you!

Medical Terms | Other Names | Learn More:HPO ID
-- | -- | --
80%-99% of people have these symptoms
Celiac disease |   | 0002608
Graves disease |   | 0100647
Hashimoto thyroiditis |   | 0000872
Primary adrenal insufficiency |   | 0008207
Type I diabetes mellitus | Type 1 diabetes[ more  ] | 0100651

**Comment by pnrobinson** [comment]
@LAB123GO  This is an error on the GARD site. I have just reported in to GARD, and hope that they will fix it shortly! Thanks for pointing this out.
