### ISSUE TITLE
Relapsing polychondritis (Adding a symptom)

### ISSUE THREAD

**Issue by natboivin** [TheJacksonLaboratory/hpo-web#138]
Tracheal Stenosis should be added to the list of symptoms for Relapsing Polychondritis.  See article below for incidence (50% of patients experience this).

https://academic.oup.com/rheumap/article/2/suppl_1/rky034.038/5104055

**Comment by pnrobinson** [comment]
The HPO shows annotations from the Orphanet project but we cannot revise those annotations ourselves.
https://hpo.jax.org/app/browse/disease/ORPHA:728
I have forwarded this to the ORPHA tracker at https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=8682&Disease_Disease_Search_diseaseGroup=relapsing&Disease_Disease_Search_diseaseType=Pat&Disease(s)/group%20of%20diseases=Relapsing-polychondritis&title=Relapsing%20polychondritis&search=Disease_Search_Simple#
