### ISSUE TITLE
Branchial cyst in Beckwith Wiedemann syndrome

### ISSUE THREAD

**Issue by Saratunon** [TheJacksonLaboratory/hpo-web#144]
Hello,
In the Beckwith Wiedemann Syndrome, "Branchial Cyst" is noted as a "frequent" clinical feature.
But, besides one case report in 1988 by Takato, I did not find in the literature branchial cyst as a typical symptom of BWS.
Can you explain me where did you find this information ?
Thank you, 
Sara

**Comment by pnrobinson** [comment]
I think you are referring to this
https://hpo.jax.org/app/browse/disease/ORPHA:116
We import these annotations from OPRHANET, and the frequencies are derived from clinical experience. 
If you think this is an error, please contact them at https://www.orpha.net/consor/cgi-bin/index.php
The HPO team controls this set of annotations
https://hpo.jax.org/app/browse/disease/OMIM:130650
We would be happy to take feedback of suggestions here.

@iimpulse  we should add a button on the HPO site to take people directly to Orphanet for feedback.

**Comment by iimpulse** [comment]
this is in the most recent release today 1.7.2 @pnrobinson. Hi @Saratunon, please refer to Peters comments. I am going to close this issue. If you have any further questions please feel to comment again, send us an email, or open another issue!

**Comment by Saratunon** [comment]
Thank you ! I will contact Orphanet.
