### ISSUE TITLE
term API could not get all disease information

### ISSUE THREAD

**Issue by rabbitdsy** [TheJacksonLaboratory/hpo-web#148]
when using  /api/hpo/term/{ontologyId}/diseases api. I could not get all the disease associations for a specific term.
Using the default example HP:0001166, there are 152 diseases associated with this term, however, the api could only get 20 of 152 (maybe the max number=20).
I could not find the parameters could change the max number, how could I get all 152 diseases?

Waiting for you reply, Thanks.

**Comment by iimpulse** [comment]
Hi @rabbitdsy,

Looks like our api docs are not complete and i apologize. Setting max=-1 will return all relations.

Let me know if this works for you.

--Mike
