### ISSUE TITLE
Download link not working

### ISSUE THREAD

**Issue by drseb** [TheJacksonLaboratory/hpo-web#151]
Seems like the download of phenotype.hpoa under https://hpo.jax.org/app/download/annotation is not working properly (tested under chrome). Can you please look into that?

Also, the linked URL must be: http://purl.obolibrary.org/obo/hp/hpoa/phenotype.hpoa

**Comment by pnrobinson** [comment]
The download link is working for me, can you try again? Maybe a temporary network issue.
@iimpulse  I agree with @drseb it would be good to link to the PURL

**Comment by drseb** [comment]
Ok. Hopefully just temporary hiccup. Thanks for checking

**Comment by drseb** [comment]
I checked again and using chrome I still get this problem:
<img width="358" alt="Screenshot 2021-01-26 at 21 28 11" src="https://user-images.githubusercontent.com/5172897/105901314-7816a480-601d-11eb-9449-92f0f4a40e37.png">

**Comment by drseb** [comment]
Best guess is some https issues? @iimpulse ?

**Comment by iimpulse** [comment]
@drseb have you still been seeing this?

**Comment by drseb** [comment]
stil not working for me.

**Comment by drseb** [comment]
there were some slack discussions about this - I think the result was that it is not solvable right now :-(

**Comment by drseb** [comment]
some minor improvement now: chrome allows me to choose "keep" from a context menu. So I think we can close. Thanks
