### ISSUE TITLE
SIX2 Orphanet gene association missing

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/hpo-web#152]
See https://github.com/obophenotype/human-phenotype-ontology/issues/6441

The association is present in the Orpha file
```
$ grep SIX2 en_product6.xml
      <Name lang="en">SIX2-related frontonasal dysplasia</Name>
            <Symbol>SIX2</Symbol>
                <Reference>SIX2</Reference>
```
@iimpulse  any idea why we are not picking this up?

**Comment by iimpulse** [comment]
@pnrobinson https://github.com/monarch-initiative/phenol/blob/90b79dd6aeceaeea75ac870ca7662ddf61d688ec/phenol-annotations/src/main/java/org/monarchinitiative/phenol/annotations/assoc/Gene2DiseaseAssociationParser.java#L184

Looks like we are creating a gene map for only those referenced in the mim2gene file. The gene map should be the unique set of all genes associated with either an OMIM or ORPHA disease.

**Comment by pnrobinson** [comment]
I think phenol has capabilities to extract the ORPHA-gene relationships. Possibly this has gotten out of date?

**Comment by iimpulse** [comment]
#210
