### ISSUE TITLE
Genes in "phenotype_to_genes" missing website pages

### ISSUE THREAD

**Issue by ACastanza** [TheJacksonLaboratory/hpo-web#156]
https://hpo.jax.org/app/browse/gene/1501
https://hpo.jax.org/app/browse/gene/7461
and maybe others give error pages reporting per:

> Could not find requested entrez id 1501.
> 
> Please ensure the query is valid by searching, otherwise please try our sample terms Atrial septal defect, Marfan Syndrome or FBN1
> 
> If you believe this is a mistake please let us know on our issue tracker.
> 

Despite being in the current HPO "phenotype_to_genes" file:
HP:0004348	Abnormality of bone mineral density	1501	CTNND2		orphadata	ORPHA:281
HP:0004348	Abnormality of bone mineral density	7461	CLIP2		orphadata	ORPHA:904

These genes also do not show up on the "Abnormality of bone mineral density" page list of genes: https://hpo.jax.org/app/browse/term/HP:0004348

**Comment by iimpulse** [comment]
This appears fixed with the rev of our phenol tool.
