### ISSUE TITLE
Can't download hp.obo file

### ISSUE THREAD

**Issue by BrightHQZ** [TheJacksonLaboratory/hpo-web#167]
Dear manager:
    I noted that the file of hp.obo and phenotype.hpoa were don't download from web page by chrome. However, the file of phenotype.hpoa could be download by wget using the command: wget http://purl.obolibrary.org/obo/hp/hpoa/phenotype.hpoa.  The file of hp.obo isn't download by wget.

Could you tell me how to download hp.obo file.

Thank you for your help.

**Comment by pnrobinson** [comment]
Hi @BrightHQZ it works for me and there should be no need to use wget.
Possibly this is related to settings for chrome on your machine?
If possible try to download with Firefox or some other browser.
This is the link: http://purl.obolibrary.org/obo/hp.obo
