### ISSUE TITLE
Extraneous frequency entries

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/hpo-web#168]
The entry for Simpson-golabi-behmel Syndrome
https://hpo.jax.org/app/browse/disease/OMIM:312870
shows many HPO terms with the feature frequency 20/20 although there is not such frequency entry in the original file.

**Comment by pnrobinson** [comment]
I think this is related to the fact that some HPO annotations are duplicated (this correlates perfectly with the pattern of 20/20 annotations online). Is it possible that having two identical annotations would somehow lead to a frequency of 20/20?

**Comment by iimpulse** [comment]
not sure what changed but these seems fixed. closing
