### ISSUE TITLE
Question about the hp.owl update

### ISSUE THREAD

**Issue by hugebeanie** [TheJacksonLaboratory/hpo-web#175]
Hello!

I am a phd student currently working on HPO ontology. I am wondering if the hp.owl from https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/master/hp.owl is constantly updating from time to time? Has the hp.owl file on the web link changed ever since the 2021 Oct 10 release? Thanks!

**Comment by pnrobinson** [comment]
Hi!
The HPO files are updated regularly -- usually every 2 months, but we missed the last release with the holidays and other obligations.
https://github.com/obophenotype/human-phenotype-ontology/releases
The new version of the release is available now.

**Comment by hugebeanie** [comment]
Thank you very much!
