### ISSUE TITLE
SSL error in API query

### ISSUE THREAD

**Issue by bheavner** [TheJacksonLaboratory/hpo-web#199]
When I attempt API queries on my mac laptop via macports curl or python 3.10.2, I get an SSL error:
```
curl -X GET "https://hpo.jax.org/api/hpo/term/HP%3A0001166" -H  "accept: application/json"
curl: (35) error:0A000152:SSL routines::unsafe legacy renegotiation disabled
```

SSLlabs [reports](https://www.ssllabs.com/ssltest/analyze.html?d=hpo.jax.org) "There is no support for secure renegotiation." for the hpo.jax.org site.

It is not clear to me whether this is an issue I should resolve on the client side by adjusting my SSL client/libraries, or if it's best resolved on the server side via an upgrade in the webserver.

**Comment by bheavner** [comment]
I can work around on the client side by enabling UnsafeLegacyRenegotiation in my `openssl.cnf` file (as described [here](via https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/1963834)) and then using the `--insecure` argument on `curl`, but of course disabling SSL functionality isn't my preferred solution.

**Comment by iimpulse** [comment]
Thanks @bheavner this has been reported a few times. We are planning to move this to the cloud soon so things should resolve. I'll leave this open and related to #197

**Comment by iimpulse** [comment]
@bheavner we got new certificates sorry for the very late resolution. But this should be working as expected now.
