### ISSUE TITLE
Generate combined gene list from multiple diseases

### ISSUE THREAD

**Issue by ymmf80** [TheJacksonLaboratory/hpo-web#206]
I would like to be able to generate a list of genes associated to an example input e.g. "Ehlers-Danlos". If I type this in HPO it will return [44 disease results from OPPHA and OMIM](https://hpo.jax.org/app/browse/search?q=ehlers%20danlos&navFilter=disease). I would like to be able to have a list of all the genes associated in this list of 44 results. What would be the best way to go about it?

**Comment by pnrobinson** [comment]
On the HPO Website, you can get lists of genes associated with specific phenotypic features. 
If you want to get genes associated with disease groups, one place to go is OMIM. For instance, here is a list of genes related to Ehlres Danlos disease: https://omim.org/phenotypicSeries/PS130000
