### ISSUE TITLE
Problem with hpo.jax.org certificate 

### ISSUE THREAD

**Issue by nlharris** [TheJacksonLaboratory/hpo-web#207]
This was reported in https://github.com/OBOFoundry/OBOFoundry.github.io/issues/2129 but is not OBO-related; it's a problem with the hpo.jax.org host.

From Slack:
Damien Goutte-Gattat:
> The “false violation” in HP’s case is not a bug in the OBO Dashboard. The problem is that the [hpo.jax.org](http://hpo.jax.org/) host (to which [www.human-phenotype-ontology.org](http://www.human-phenotype-ontology.org/) is redirected) is badly configured: it only sends its own certificate, without the chain of certificates needed to validate it.
It works when you connect to [www.human-phenotype-ontology.org](http://www.human-phenotype-ontology.org/) with a web browser (such as Firefox, Safari, etc.) only because most browsers deal with incomplete (or absent) certificate chains by reconstructing a chain themselves using all their own local cache of intermediate certificates. But non-browser clients (e.g. tools like wget, curl, and software libraries like Python’s requests, etc.) can’t do that.
Bottom line: someone at [jax.org](http://jax.org/) needs to fix the configuration of their webserver.

Sebastian Köhler
> Are you sure that jax is the one that defines the redirect? I thought this was made by our old employee, the charite in Berlin. If it is jax, then it should be easy to improve. I will contact Peter/Mike. (Why is peter Robinson not in the obo-slack? :scream:)

Damien Goutte-Gattat
> No, the redirection is done by whoever is running the [www.human-phenotype-ontology.org](http://www.human-phenotype-ontology.org/) host (141.42.207.15) – which indeed appears to be “Charite - Universitaetsmedizin Berlin”.
But the redirection itself is not the problem. It’s working fine, there’s nothing to fix there. What needs to be fixed is the server we are redirected to ([hpo.jax.org](http://hpo.jax.org/), 64.147.57.24) – that’s the one that is misconfigured.

Please see https://github.com/OBOFoundry/OBOFoundry.github.io/issues/2129 for more details.

**Comment by iimpulse** [comment]
Yes, discussing with JAX IT and getting new certs.
