### ISSUE TITLE
Internet explorer support

### ISSUE THREAD

**Issue by dominickdm** [TheJacksonLaboratory/hpo-web#230]
Since some weeks, the hpo site (https://hpo.jax.org/app/) doesn’t work anymore on Internet explorer (version 11). I know Microsoft has dropped support for this version, but still a lot of our customers use internet explorer to access this web page.
Is IE11 blocked on purpose? Is there any way that we can get it working again for Internet Explorer 11?

Screenshot: empty page in Internet explorer,  no JS errors shown.
![image](https://user-images.githubusercontent.com/40289256/210244527-e1b8d711-2bb9-4916-9bd1-f94ddfd734af.png)

**Comment by iimpulse** [comment]
Hi @dominickdm, please refer to our email on this one
