### ISSUE TITLE
Stable link to ontologies

### ISSUE THREAD

**Issue by Zethson** [TheJacksonLaboratory/hpo-web#237]
Hi,

unfortunately the buttons on https://hpo.jax.org/app/data/ontology are autogenerated and I cannot figure out which links point to the latest stable release. Do you have such links and what are they?

Thanks

**Comment by pnrobinson** [comment]
This page has the original version
https://github.com/obophenotype/human-phenotype-ontology
see here for the releases
https://github.com/obophenotype/human-phenotype-ontology/releases
