### ISSUE TITLE
download links not working

### ISSUE THREAD

**Issue by nberkow** [TheJacksonLaboratory/hpo-web#241]
Trying to download json from:

https://hpo.jax.org/app/data/ontology

Chrome:
Version 110.0.5481.180 (Official Build) (64-bit)

The link briefly opens a new tab and closes it without triggering a download. Enabling pop-ups doesn't affect the behavior.

**Comment by pnrobinson** [comment]
@iimpulse I can confirm that I can download from Firefox but not from Chrome -- exactly as reported by @nberkow

**Comment by iimpulse** [comment]
#248

Hardlinking to latest release. Purl doesnt support http yet.
