### ISSUE TITLE
Navigation to HPO download from lirical.readthedocs.io goes to a page that does not exist.

### ISSUE THREAD

**Issue by adeslatt** [TheJacksonLaboratory/hpo-web#243]
@pnrobinson I am in a Chrome Browser and I navigated to the HPO download from https://lirical.readthedocs.io/en/latest/tutorial.html.   Specifically here. 

> To set up PhenopacketGenerator, you will first need to set the location of the hp.obo file. Download hpo.obo from the [Download page](https://hpo.jax.org/app/download/ontology) of the HPO website. Enter your Biocurator id by selecting “Set biocurator id” from the edit menu, and enter an arbitrary Phenopacket ID and proband ID. Use the dropdown menus to enter “9 years” for Age and “Female” for sex.

<img width="1253" alt="Screen Shot 2023-03-21 at 9 26 23 AM" src="https://user-images.githubusercontent.com/3410127/226620102-52e9db5f-18d1-49a1-969d-b547296574f7.png">

**Comment by iimpulse** [comment]
in favor of https://github.com/TheJacksonLaboratory/LIRICAL/issues/584. Change has been committed to master.
