### ISSUE TITLE
Could not find requested HP:0000118.

### ISSUE THREAD

**Issue by jon4thin** [TheJacksonLaboratory/hpo-web#255]
Could not find requested HP:0000118.
<img width="895" alt="Screen Shot 2023-06-12 at 4 39 02 PM" src="https://github.com/TheJacksonLaboratory/hpo-web/assets/59671833/c7d93dd8-7bbe-44ad-855b-1a2ac98b95ab">

**Comment by pnrobinson** [comment]
It works for me -- see https://hpo.jax.org/app/browse/term/HP:0000118
Could you provide more context about how this error occured?
