### ISSUE TITLE
Show translations of definition and synonyms

### ISSUE THREAD

**Issue by turnovec** [TheJacksonLaboratory/hpo-web#269]
It's really nice that it's now possible to switch to different languages. But currently it only shows translation of main term. Would it be possible to show (on term page) also the translation of definition and synonyms?

**Comment by iimpulse** [comment]
Currently the translations are part of a larger project and require specific language experts to do the translation. I'm not sure of the status of these. @pnrobinson @matentzn

**Comment by pnrobinson** [comment]
I believe we have translations of the definitions etc for some languages and some terms (less than for labels, but still a lot). I think the suggestions is to show the translated definitions if possible, otherwise to fall back on English.

**Comment by iimpulse** [comment]
Hi guys, looks like we had this the whole time. I just needed to wire it in, for the translations that don't have definitions we default back to english. #279
