### ISSUE TITLE
Domain Issues

### ISSUE THREAD

**Issue by iimpulse** [TheJacksonLaboratory/hpo-web#271]
Checked means we have received data and no errors. This also fails for https://hpo.jax.org. 

Personal Machine - Command Line - Debian Buster
- [x] wget https://poet.jax.org
- [x] curl https://poet.jax.org

Personal Machine - Docker Container - https://hub.docker.com/r/obolibrary/odkfull
- [ ] wget https://poet.jax.org
- [ ] curl https://poet.jax.org

JAX Machine - Command Line - Ventura 13.1
- [ ] wget https://poet.jax.org
- [x] curl https://poet.jax.org
- [x] wget http://cthpo02lt.jax.org
- [x] curl http://cthpo02lt.jax.org

JAX Machine - Docker Container - https://hub.docker.com/r/obolibrary/odkfull
- [ ] wget https://poet.jax.org
- [ ] curl https://poet.jax.org
- [x] wget http://cthpo02lt.jax.org
- [x] curl http://cthpo02lt.jax.org

Internal VM: cthpo02lt.jax.org

**Comment by tjwhitt** [comment]
![image](https://github.com/TheJacksonLaboratory/hpo-web/assets/100785547/9f774557-7574-4e64-b509-bf4c5a37027e)

**Comment by iimpulse** [comment]
<img width="635" alt="image" src="https://github.com/TheJacksonLaboratory/hpo-web/assets/7397665/043a7a19-64cf-47da-ade9-2988ed046803">

**Comment by iimpulse** [comment]
Closing as complete @tjwhitt , can still view the information here in closed tickets. Thanks so much for your help.
