### ISSUE TITLE
MONDO xref wrong for ORPHA Disease terms on HPO annotation pages

### ISSUE THREAD

**Issue by peupeubangbang** [TheJacksonLaboratory/hpo-web#289]
Hi @iimpulse I'm not sure if this is an upstream issue say in MONDO or ORDO but...

Currently all ORPHA diseases display an incorrect MONDO xref weblink to  **MONDO:0011929** when browsing their HPO annotations on the website. 

The definition is the same (incorrect again from MONDO:0011929) for each ORPHA disease as well. 

I checked HPOA as well as MONDO owl files and couldn't see anything funny. So I was wondering if there was something going on at another source from where HPO consumes MONDO xrefs and definitions for ORPHA diseases? (I don't know how this occurs)

Also see:
obophenotype/human-phenotype-ontology#10558

**Comment by matentzn** [comment]
@peupeubangbang can you report this here: https://github.com/monarch-initiative/mondo/issues? The problem is in Mondo: https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0011929

Thanks!
