### ISSUE TITLE
Search terms not retrieving in results

### ISSUE THREAD

**Issue by peupeubangbang** [TheJacksonLaboratory/hpo-web#304]
Probably already on your radar @iimpulse but just in case... 

Having issues with search functionality on HPO website with not retrieving any terms, just get the loading bar. 

Those in the search box drop down showing 10 suggested Phenotype terms seem to load just fine when selecting them.

Also not getting any disease or gene results and spotted an error message earlier something to do with ontologies not loading (sorry forgot to screenshot). Also don't get any drop down suggestions for diseases or genes when searching using disease or gene filter in search box.

HPO is loading in EBI OLS and phenotype annotations for MONDO IDs are on Monarch Initiative so can use those as a backup for now. 

Thanks as always for any help you can provide!

**Comment by iimpulse** [comment]
This was not on my radar and it always happens when im about to go on vacation. We were stable for 2 months :D. Rebooted the rooster yesterday should be all good. Appreciate it.
