### ISSUE TITLE
Nice to have: clarity on what is meant by number of decendants

### ISSUE THREAD

**Issue by jmcmurry** [TheJacksonLaboratory/hpo-web#4]
<img width="198" alt="screen shot 2018-02-08 at 10 30 17 pm" src="https://user-images.githubusercontent.com/3658863/36017716-b96cae34-0d2d-11e8-8f07-82acef8db612.png">

On tooltips etc, perhaps worth clarifying that the number is the number of _direct_ descendants rather than just "descendants"?

**Comment by iimpulse** [comment]
<img width="864" alt="Screen Shot 2019-04-12 at 11 59 35 AM" src="https://user-images.githubusercontent.com/7397665/56050695-8b5a6200-5d1a-11e9-90bc-66eac708ead9.png">


@jmcmurry @pnrobinson hows this implementation?

**Comment by jmcmurry** [comment]
Wow! This is great. As long as there is a tooltip explaining what it is, I think this is great. Nice work.

**Comment by iimpulse** [comment]
#69
