### ISSUE TITLE
Monarch / MONDO linkouts

### ISSUE THREAD

**Issue by jmcmurry** [TheJacksonLaboratory/hpo-web#41]
We should roll this out in stages.

- [ ]  Step 1. Link out using existing identifiers. (see #40)

HPO-Web curie | Monarch curie | Monarch URL example
------|--------|---------
````ORPHA:```` | ````Orphanet:````| https://monarchinitiative.org/Orphanet:276413
````OMIM:```` | ````OMIM:````| https://monarchinitiative.org/OMIM:612242
NCBI Gene (numeric fragments only are displayed) | ````NCBIGene:```` | https://monarchinitiative.org/NCBIGene:6622

- [ ] Step 2. Change the HPO Web DB back end to use MONDO IDs natively.

**Comment by iimpulse** [comment]
@jmcmurry @pnrobinson I see a bunch of linked issue, where did this discussion end up?

**Comment by pnrobinson** [comment]
I think that we are ready for step 1, perhaps with a link like "<a href=...>View DISEASENAME on Monarch Initiative Website</a>
We should start to scope step 2

**Comment by cmungall** [comment]
Needs to be changed in MONDO

>

**Comment by iimpulse** [comment]
Finally implementing basic linkouts... will open a new ticket for complete MONDO overhall
