### ISSUE TITLE
Search for Disease IDs

### ISSUE THREAD

**Issue by drseb** [TheJacksonLaboratory/hpo-web#44]
Why is  a search for "OMIM:160900" or "160900" not giving any results? The disease is there and can be found by the disease name. Is this intentional?

@pnrobinson @iimpulse

**Comment by jmcmurry** [comment]
from experience, I recommend wiring it up to expect these kinds of permutations:
````
154700
OMIM:154700
MIM:154700
OMIM_154700
MIM_154700
````
