### ISSUE TITLE
Add a feedback button with link to github issues

### ISSUE THREAD

**Issue by jmcmurry** [TheJacksonLaboratory/hpo-web#45]
Now that this repo is public, please add a link to the GitHub issues from the UI.
I suggest adding "Request a feature / report a bug" to the FAQ. From there link to the hpo-web or hpo depending on what kind of issue it is.

**Comment by jmcmurry** [comment]
If possible, yes, thanks :)

**Comment by jmcmurry** [comment]
This is good enough; however, if possible, the link should be https://github.com/TheJacksonLaboratory/hpo-web/issues/new rather than just /issues

**Comment by iimpulse** [comment]
Will do!
