### ISSUE TITLE
Allow download of (page-specific) annotations as tsv

### ISSUE THREAD

**Issue by jmcmurry** [TheJacksonLaboratory/hpo-web#49]
While the dumps have [now been linked](https://github.com/TheJacksonLaboratory/hpo-web/issues/27) (I think), there still needs to be a .tsv download option provided at the level of disease pages and term pages. The downloads (at a minimum, but perhaps also the UI) should explicitly state the provenance of the associations, even if this is exclusively showing those we have curated ourselves.

**Comment by iimpulse** [comment]
We've had this in our internal backlog. But I've moved away from that and started using the PM tools here. I'll make this a strech because I haven't implemented this before. So I don't want to over promise when i start these issues next week.

**Comment by iimpulse** [comment]
My current working prototype, allows you to select genes or disease associations on the term page. Do we think that there should be one button that exports everything to an excel sheet ( each association on a different sheet ) or select a specific association only? This functionality will be implemented on the other two pages as well.

@jmcmurry @pnrobinson

**Comment by jmcmurry** [comment]
Agreed a single type at a time should be adequate

>

**Comment by jmcmurry** [comment]
I currently get a 500 here https://hpo.jax.org/api/hpo/download/disease?identifier=ORPHA:558&association=terms

**Comment by iimpulse** [comment]
I've removed the button for now. I'll have to debug and also stand up a test server so things like this don't happen.

**Comment by iimpulse** [comment]
@jmcmurry @pnrobinson @drseb This should be fixed. The package failed to support syntax when building in to a war file. Please test for validity! I will close upon approval.

**Comment by pnrobinson** [comment]
This works for me!

**Comment by jmcmurry** [comment]
Works for me too; I LOVE that the categories are explicitly stated. 

It is fine to close this issue for now, however, I do think on balance it is preferable to have the subject of the relationship and the provenance on every row. Perhaps open up a new ticket for that aspect though.

**Comment by pnrobinson** [comment]
@pnrobinson @iimpulse 
Currently, we do not ingest the disease-gene associations from Orphadata
http://www.orphadata.org/cgi-bin/index.php
We should add this to phenol--I will open an issue
