### ISSUE TITLE
Make FAQ-items linkable

### ISSUE THREAD

**Issue by drseb** [TheJacksonLaboratory/hpo-web#50]
each question should have its own link.

**Comment by iimpulse** [comment]
Hi Seb,

Are you saying that each question should be on its own page? An alternative might be to have a link that will open and scroll to that question automatically. Let me know what you think.

--Mike

**Comment by drseb** [comment]
Hi,
I think they can stay on one page. Just a solution with anchors or the like. Thanks

**Comment by iimpulse** [comment]
Seb,

You can now link to specific issues via the url

https://hpo.jax.org/app/faq/1

Where the number is the question starting from 1 to the bottom.

Let me know what you think!

**Comment by drseb** [comment]
Great! Thanks. Shall we align the whole thing center? The header is centered, the actual FAQs not. I will close this issue. Let me know if I should make a new issue regarding the alignment.
