### ISSUE TITLE
Publication Integration

### ISSUE THREAD

**Issue by iimpulse** [TheJacksonLaboratory/hpo-web#54]
We would like to integrate HPO publications into zotero and access them via the rest api.

**Comment by iimpulse** [comment]
Peter will implement his own zotero and store publications in github

**Comment by iimpulse** [comment]
![Screen Shot 2019-03-21 at 3 07 31 PM](https://user-images.githubusercontent.com/7397665/54781403-9413b880-4bf2-11e9-9649-8ac421d7ed66.png)

![Screen Shot 2019-03-21 at 3 06 57 PM](https://user-images.githubusercontent.com/7397665/54781439-a8f04c00-4bf2-11e9-9c38-edf212b66dfa.png)


@jmcmurry  Are you able to provide some feedback on this new implementation of the publications page?

**Comment by jmcmurry** [comment]
It looks very nice, but I'm not sure what I'm looking at; what do the categories mean? Are we able still to pull out the categories I suggested?

**Comment by iimpulse** [comment]
Topics are tags which is the drop down is open. Categories should probably be a radio button that will just be "all" or "by us"
@pnrobinson

**Comment by pnrobinson** [comment]
@jmcmurry  The categories are from PubMan https://github.com/monarch-initiative/pubman
It would be possible, but not easy, to revise the categories -- but I think we have the major categories that our users will be familiar with

**Comment by pnrobinson** [comment]
@iimpulse , @jmcmurry -- Can we reorder the columns to
1. Author (up to three author names; if >3 authors, replace with Smith et al). Put a link to PubMed here
2. Year
3. Title
4. Journal

**Comment by pnrobinson** [comment]
@jmcmurry  -- can you think of a better way to say "by us"? This category basically means an article where one of the HPO people was an important author (usually first or last or both). There are other articles where one of us was a coauthor but not really a major contributor, these (and many others) are included in "all"

**Comment by jmcmurry** [comment]
I'm sure that the categories and types you landed on are important; however, I'm ... not at all sure what they mean -- even as an insider. Therefore please explain them in some way; the easiest way to achieve this would be tool tips or an info box. Another alternative would be to add two columns (for type and category). Seeing the pubs tagged in this way, with tooltips may help explain why they are there? Kudos as this looks very powerful but it doesn't yet feel intuitive.

**Comment by iimpulse** [comment]
#69 NEW TICKET #70
