### ISSUE TITLE
Auto-Complete suggestion 

### ISSUE THREAD

**Issue by iimpulse** [TheJacksonLaboratory/hpo-web#56]
Update highlighting technique to be more in line with proper ui standards and make the output full width of the search plus the filter, fix the filter width to be like amazon.

I feel like we should be updating all references to "Terms" -> "Phenotypes"  for example the heading of the category in autocomplete.

![image](https://user-images.githubusercontent.com/7397665/51013137-db186a00-152e-11e9-8b56-94dfd438011b.png)

@jmcmurry @pnrobinson @drseb

**Comment by jmcmurry** [comment]
Looks great!

**Comment by iimpulse** [comment]
<img width="526" alt="screen shot 2019-01-11 at 4 49 40 pm" src="https://user-images.githubusercontent.com/7397665/51061336-f03dd900-15c0-11e9-99fd-9289d89ca9c4.png">

thoughts?? Going to change a few more things. @jmcmurry

**Comment by drseb** [comment]
I like it

**Comment by jmcmurry** [comment]
I guess I prefer the former as it feels more standard, but don't object to the latter.

**Comment by iimpulse** [comment]
I've got a few ideas to mix the two. I just felt as if the former felt a little out of date highlighting wise. So I can mix the top blue with the highlighting but revert some of the placement of the categories

**Comment by drseb** [comment]
I would vote for the blue thingy...

**Comment by pnrobinson** [comment]
Not sure what the blue thingy is, I can see at least two blue thingies, but both options look great :-0

**Comment by iimpulse** [comment]
Following some amazon verbiage. Once I get this working on all devices, this will be the final upgrade.

<img width="515" alt="screen shot 2019-01-13 at 12 38 18 pm" src="https://user-images.githubusercontent.com/7397665/51088651-3cf3f200-1730-11e9-9bac-a31d73620901.png">
