### ISSUE TITLE
JanusGraph Migration

### ISSUE THREAD

**Issue by iimpulse** [TheJacksonLaboratory/hpo-web#60]
Migrate existing relational schema to a standalone implementation of JanusGraph using Tinkerpop/Gremlin

**Comment by cmungall** [comment]
Interesting - as you know we use Neo4J in the Monarch stack, I wonder if we can share some modeling patterns? The use of tinkerpop/gremlin should help abstract away from graph-db specific differences. Would someone from the hpo-web team be interested in speaking about this on a monarch huddle?

cc @kshefchek @pnrobinson

**Comment by iimpulse** [comment]
Not going to happen.
