### ISSUE TITLE
LOINC Integration

### ISSUE THREAD

**Issue by iimpulse** [TheJacksonLaboratory/hpo-web#63]
- [ ]  Create endpoint for getting LOINC information based on search.

- [ ]  Create  a controller that links the to the endpoint.

- [ ]  Create a service (class) that will either query the db or get its information from an in memory bean and have it get called from the controller

- [ ]  Create a view ( json blueprint ) for the controller to return

@pnrobinson Here are some basic steps to get the LOINC code information to the public site. I believe it would be in Aaron's best interest to implement these step to get to learn rest-apis.

Please let me know if this makes sense.

**Comment by pnrobinson** [comment]
Seems like a good plan. I would also be interested in understanding more about serving REST APIS...

**Comment by kingmanzhang** [comment]
@iimpulse Let's talk some time next week on the rendering part.

**Comment by kingmanzhang** [comment]
@iimpulse I added some tests and it seems working to get a set of LOINC entries from an HPO termId. Could you double check the tests are working? I haven't made mocking work but have to get around that. If it works, we can move on to views.

**Comment by iimpulse** [comment]
@kingmanzhang checkout #66

**Comment by iimpulse** [comment]
#69
