### ISSUE TITLE
Publication Filter Update

### ISSUE THREAD

**Issue by iimpulse** [TheJacksonLaboratory/hpo-web#70]
Make the publication filter more user friendly

**Comment by jmcmurry** [comment]
I can't seem to even find the publications page. Is it up?

**Comment by pnrobinson** [comment]
help/information/Publications

https://hpo.jax.org/app/help/publications

Perhaps it is too well hidden?

**Comment by iimpulse** [comment]
Not really sure what this was about.. so closing.
