### ISSUE TITLE
Add link to PMIDs for definitions

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/hpo-web#71]
![image](https://user-images.githubusercontent.com/4943420/56306655-08b61600-6111-11e9-8098-feefa60cc0c2.png)

For instance, for this term, link out to  https://www.ncbi.nlm.nih.gov/pubmed/27036365
Optimally, also show the title of the PMID (Hyperketonemia and ketosis increase the risk of complications in type 1 diabetes. etc)

**Comment by pnrobinson** [comment]
Probably  org.monarchinitiative.phenol.ontology.data.Term;
```
  /**
   * These are the cross-references that go along with the definition. In the case of the HPO, these
   * are often PubMed ids.
   */
  private final List<SimpleXref> databaseXrefs;
```
Use this convenience function
```
/**
   * Get all of the pub med references attached to the definition of this term
   */
  public List<SimpleXref> getPmidXrefs() {
    return databaseXrefs.stream().filter(SimpleXref::isPmid).collect(Collectors.toList());
  }
```

Create URL with  String getId() {
    return id;
  }

**Comment by iimpulse** [comment]
#90 released.
