### ISSUE TITLE
Define order of categories for diseases.

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/hpo-web#72]
Inheritance should go first

**Comment by iimpulse** [comment]
Anything else here? @pnrobinson

**Comment by pnrobinson** [comment]
e.g., take these categories
```
private static final TermId INHERITANCE_ID = TermId.of("HP:0000005");
    private static final TermId ABNORMAL_CELLULAR_ID = TermId.of("HP:0025354");
    private static final TermId BLOOD_ID = TermId.of("HP:0001871");
    private static final TermId CONNECTIVE_TISSUE_ID = TermId.of("HP:0003549");
    private static final TermId HEAD_AND_NECK_ID = TermId.of("HP:0000152");
    private static final TermId LIMBS_ID =TermId.of("HP:0040064");
    private static final TermId METABOLISM_ID = TermId.of("HP:0001939");
    private static final TermId PRENATAL_ID = TermId.of("HP:0001197");
    private static final TermId BREAST_ID = TermId.of("HP:0000769");
    private static final TermId CARDIOVASCULAR_ID = TermId.of("HP:0001626");
    private static final TermId DIGESTIVE_ID = TermId.of("HP:0025031");
    private static final TermId EAR_ID = TermId.of("HP:0000598");
    private static final TermId ENDOCRINE_ID = TermId.of("HP:0000818");
    private static final TermId EYE_ID = TermId.of("HP:0000478");
    private static final TermId GENITOURINARY_ID = TermId.of("HP:0000119");
    private static final TermId IMMUNOLOGY_ID = TermId.of("HP:0002715");
    private static final TermId INTEGUMENT_ID = TermId.of("HP:0001574");
    private static final TermId MUSCLE_ID = TermId.of("HP:0003011");
    private static final TermId NERVOUS_SYSTEM_ID = TermId.of("HP:0000707");
    private static final TermId RESPIRATORY_ID = TermId.of("HP:0002086");
    private static final TermId SKELETAL_ID = TermId.of("HP:0000924");
    private static final TermId THORACIC_CAVITY_ID = TermId.of("HP:0045027");
    private static final TermId VOICE_ID = TermId.of("HP:0001608");
    private static final TermId CONSTITUTIONAL_ID = TermId.of("HP:0025142");
    private static final TermId GROWTH_ID = TermId.of("HP:0001507");
    private static final TermId NEOPLASM_ID = TermId.of("HP:0002664");
```

And order them a little more @pnrobinson

**Comment by pnrobinson** [comment]
@iimpulse  Let's go with the following. Please note that the category BLOOD_ID was missing from this list originally and I think is not showing on our website (e.g., try to find http://cthpo02lt:8080/app/browse/term/HP:0011029 on a disease annotation page) 
-- I will add this to phenol in the next release

private static final TermId INHERITANCE_ID = TermId.of("HP:0000005");
private static final TermId GROWTH_ID = TermId.of("HP:0001507"); 
private static final TermId HEAD_AND_NECK_ID = TermId.of("HP:0000152");
private static final TermId EAR_ID = TermId.of("HP:0000598");
private static final TermId EYE_ID = TermId.of("HP:0000478");
private static final TermId CARDIOVASCULAR_ID = TermId.of("HP:0001626");
private static final TermId RESPIRATORY_ID = TermId.of("HP:0002086");
private static final TermId THORACIC_CAVITY_ID = TermId.of("HP:0045027");
private static final TermId BREAST_ID = TermId.of("HP:0000769");
private static final TermId DIGESTIVE_ID = TermId.of("HP:0025031");
private static final TermId ENDOCRINE_ID = TermId.of("HP:0000818");
private static final TermId GENITOURINARY_ID = TermId.of("HP:0000119");
private static final TermId IMMUNOLOGY_ID = TermId.of("HP:0002715");
private static final TermId BLOOD_ID = TermId.of("HP:0001871");
private static final TermId SKELETAL_ID = TermId.of("HP:0000924");
private static final TermId MUSCLE_ID = TermId.of("HP:0003011");
private static final TermId LIMBS_ID =TermId.of("HP:0040064");
private static final TermId CONNECTIVE_TISSUE_ID = TermId.of("HP:0003549");
private static final TermId INTEGUMENT_ID = TermId.of("HP:0001574");
private static final TermId NERVOUS_SYSTEM_ID = TermId.of("HP:0000707");
private static final TermId VOICE_ID = TermId.of("HP:0001608");
private static final TermId PRENATAL_ID = TermId.of("HP:0001197");
private static final TermId CONSTITUTIONAL_ID = TermId.of("HP:0025142");
private static final TermId NEOPLASM_ID = TermId.of("HP:0002664");
private static final TermId METABOLISM_ID = TermId.of("HP:0001939");
private static final TermId ABNORMAL_CELLULAR_ID = TermId.of("HP:0025354");

**Comment by iimpulse** [comment]
#90 released.
