### ISSUE TITLE
Minor issue with hpo search tool

### ISSUE THREAD

**Issue by LCCarmody** [TheJacksonLaboratory/hpo-web#73]
When searching a term on the main page, everything works fine.  However, once I navigate to a page (ex. https://hpo.jax.org/app/browse/term/HP:0003829) and then use the search tool in the upper right, I have issues. When typing in a term, it auto suggests, however, when I scroll down to that suggestion, it will not navigate to that page  **sometimes**.  Sometimes it works--just not the first time...and I am not entirely sure why. Also, less of an issue, the up and down arrows can't be used to scroll through the list.

Mac, google chrome

**Comment by iimpulse** [comment]
hi @LCCarmody the navigating should be fixed. Thanks for pointing it out. Let me know if everything seems okay now

**Comment by iimpulse** [comment]
#74
