### ISSUE TITLE
Terms with multiple comments?

### ISSUE THREAD

**Issue by sdumitriu** [TheJacksonLaboratory/hpo-web#75]
In the April release there are two terms with multiple `comment` fields: `HP:0002282` and `HP:0032497`. This seems new in this release, our assumption so far has been that only one comment per term is allowed. Is this an error in the release, or should we change our assumption to support fields with multiple comments?

**Comment by pnrobinson** [comment]
Terms should never have more than one comment. There was a recent error that has been corrected, and we are going to improve the Q/.C pipeline to catch these errors before releases in the future.

**Comment by iimpulse** [comment]
https://github.com/obophenotype/human-phenotype-ontology/issues/4817
