### ISSUE TITLE
Entrez API error

### ISSUE THREAD

**Issue by andrewSharo** [TheJacksonLaboratory/hpo-web#78]
Received an Entrez API error that asked me to report it. Happened on the following page:
https://hpo.jax.org/app/browse/gene/54936

Thanks for building such an otherwise helpful resource :)

**Comment by iimpulse** [comment]
Thanks @andrewSharo ! Did you manually type in the entrez id into the url bar or navigated from an association?

**Comment by andrewSharo** [comment]
I don't recall, but when I search the database for ADPRHL2, I am able to get the error again. I'm using chrome with several privacy plugins like Privacy Badger and uBlock Origin

**Comment by iimpulse** [comment]
Seems to be working for me currently. Can you try to clear your cache? I'll keep an eye out on this. Something was a little funky here.

**Comment by iimpulse** [comment]
Closing. Please reopen if you see continued errors.
