### ISSUE TITLE
Add term frequency onset for term -> disease

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/hpo-web#80]

**Comment by pnrobinson** [comment]
For pages like this
https://hpo.jax.org/app/browse/disease/OMIM:216550
we could put the definition as a popup (mouse over) and instead put the frequency, modifiers (if any), onset, and a list of pubmed or OMIM references to the source of the annotation.
@jmcmurry ideas about the layout?

**Comment by jmcmurry** [comment]
There's a lot to unpack here: Adding the frequency and modifiers would be awesome, but that would seem to be another column in the tables below. There appears to be room there; I think worth a try, perhaps as column 2 after the ID. The question is how to deal with conflicting frequencies from different sources. Whether one or multiple, it would be good to expand the frequency/modifier information on demand to show the OMIM or PubMed source. Where these have been asserted by us via HPOA, worth stating. 

On a usability note, click is more mobile friendly than is hover; however, I'm also not sure how much we care about that for our app.

As for the textual definition of the disease itself, it would be great to include that at the top too. Most of the definitions are short enough, but the box could scroll for the longer ones.

**Comment by iimpulse** [comment]
#90 released.

**Comment by jmcmurry** [comment]
Thanks Mike. This is a definite improvement, however I would recommend we now try to represent the source in a way that is clear what the source is referring to being the source of.  I will make another ticket.
