### ISSUE TITLE
Clarify the provenance of associations and frequencies

### ISSUE THREAD

**Issue by jmcmurry** [TheJacksonLaboratory/hpo-web#93]
The current UI is a bit confusing with respect to the source of the d2p associations versus the additional frequency / onset annotations. Below a proposal for discussion:

![image](https://user-images.githubusercontent.com/3658863/66780042-b322b200-ee84-11e9-95d2-14edc95d89b4.png)

**Comment by pnrobinson** [comment]
The PMID or OMIM source refers to everything in the entire line! Not all annotations are OMIM-sourced. 
Can we skype about how to improve the pages?

**Comment by iimpulse** [comment]
#114  released changes here.
