### ISSUE TITLE
Only OMIM data used for searching gene<->phenotype associations?

### ISSUE THREAD

**Issue by roland-ewald** [TheJacksonLaboratory/hpo-web#94]
This seems somewhat related to #93 (and maybe #57 ), but we noticed that the HPO browser only provides results based on the gene-phenotype relations from OMIM, but not those from Orphanet?

If so, this may be a helpful addition to the FAQ, to avoid confusion.

## Example: `ARVCF`

- `ARVCF` is linked with `22q11.2 deletion syndrome` [in Oprhanet](https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&type_list=disease&data_id=15954&Gene%20name%20or%20symbol=ARVCF-delta-catenin-family-member---ARVCF&search=Disease_Search_Simple&Disease_Disease_Search_diseaseGroup=ARVCF&Disease_Disease_Search_diseaseType=Gen)
- `ARVCF` has relations to HPO terms in the latest [`ALL_SOURCES_FREQUENT_FEATURES_genes_to_phenotype.txt`](http://compbio.charite.de/jenkins/job/hpo.annotations.monthly/157/artifact/annotation/ALL_SOURCES_FREQUENT_FEATURES_genes_to_phenotype.txt) file
- `ARVCF`  has relations to HPO terms in the latest [`ORPHA_FREQUENT_FEATURES_genes_to_phenotype.txt`](http://compbio.charite.de/jenkins/job/hpo.annotations.monthly/157/artifact/annotation/ORPHA_FREQUENT_FEATURES_genes_to_phenotype.txt) file
- `ARVCF` has _no_ relations in the latest [`OMIM_ALL_FREQUENCIES_genes_to_phenotype.txt`](http://compbio.charite.de/jenkins/job/hpo.annotations.monthly/157/artifact/annotation/OMIM_ALL_FREQUENCIES_genes_to_phenotype.txt) file

**Comment by pnrobinson** [comment]
The above mentioned gene<->HPO links are incorrect in my opinion because 22q11.2 comprises multiple genes and we do not know which gene is/which genes are related to which phenotype. But we need to explore other Orphanet data better and document this on the website better, thanks for pointing this out!

**Comment by roland-ewald** [comment]
@pnrobinson thanks for the quick response! This makes sense.

**Comment by cruckert** [comment]
I have a similar problem, the FAQ states genes_to_phenotypes.txt is used for phenotype to gene association, but which one?
For HP:0010915 the browser shows 23 associated genes

But the files contain (hpo.annotations.monthly build 157):
All Sources + All frequencies: 34 genes
All Sources + frequent: 33 genes
Omim all frequencies: 17 genes
Omim frequent: 16 genes

Which source is used by the HPO browser? Are these further filtered?

I stumbled on this as some of the genes from the downloadable lists not shown in the browser are no official HGNC gene symbols e.g. TRNK

**Comment by iimpulse** [comment]
@cruckert please see #105 , sorry for the super delayed response.
